/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kibat6204
 */
import javax.swing.ButtonGroup;
public class adventureProgramGUI extends javax.swing.JFrame {

    /**
     * Creates new form adventureProgramGUI
     */
    public adventureProgramGUI() {
        initComponents();
        groupButton();
        outputField.setText("Your are a spy.  \nyour job is to find the villain.  \nDo you accept? \nA = yes \n B = no");
    }
    
    private void groupButton() {
        
        ButtonGroup bg1 = new ButtonGroup();
        
        bg1.add(bButton);
        bg1.add(aButton);
        bg1.add(cButton);
        
        cButton.setVisible(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    int counter = 0;
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cButton = new javax.swing.JRadioButton();
        resultField = new javax.swing.JLabel();
        aButton = new javax.swing.JRadioButton();
        bButton = new javax.swing.JRadioButton();
        goButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        resultField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        aButton.setText("A");
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });

        bButton.setText("B");
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });

        goButton.setText("GO");
        goButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goButtonActionPerformed(evt);
            }
        });

        outputField.setColumns(20);
        outputField.setRows(5);
        jScrollPane1.setViewportView(outputField);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(aButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                        .addComponent(bButton))
                    .addComponent(resultField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cButton)
                    .addComponent(goButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bButton)
                    .addComponent(aButton)
                    .addComponent(cButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(goButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        
    }//GEN-LAST:event_aButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        
    }//GEN-LAST:event_bButtonActionPerformed

    private void goButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goButtonActionPerformed
        
        counter = counter + 1;
        goButton.setText("GO");
        cButton.doClick();
        
        if (counter == 1)
        {
            outputField.setText("You walk into the building. \nYou see two doors. \nOne is broken and easy to kick down. \nThe other is made of iron. \n\nA = Use explosive charge to destroy iron door\nB = Kick down broken door");
            if (bButton.isSelected())
            {
                cButton.doClick();
            }
            
            if (aButton.isSelected())
            {
                outputField.setText("The bad guy runs out of the building and kills you.");
                goButton.setText("Try Again");
                cButton.doClick();
                counter = 0;
            }
        }
        
        if (counter == 2)
        {
            outputField.setText("You kick down the broken door to find an elavator. \nThe door is open and the buttons appear to be \nworking. \nThere is, however, a hole in the roof. \n\nA = Crawl through the hole and climb up the cable \nB = Use the elavator as normal");
            if (bButton.isSelected())
            {
                cButton.doClick();
            }
            
            if (aButton.isSelected()) 
            {
                outputField.setText("You use your explosive device to destroy the door. \nThere are large quantities of TNT behind the door. \nThe explosion is too large for you to survive. ");
                goButton.setText("Try Again");
                cButton.doClick();
                counter = 0;
            }
        }
        
        if (counter == 3)
        {
            outputField.setText("You slowly shimmy up the elavator cable \nto the next floor. \nYou can hear sounds down the hallway. \nYou check your gun and realize\nyou are low on ammo. \nYou also see some extra ammo lying on the ground. \nA = Load the ammo \nB = Leave with what you have");
            if (aButton.isSelected())
            {
                cButton.doClick();
            }
            
            if (bButton.isSelected())
            {
                outputField.setText("You press the up button in the elavator. \nIt is rigged by the bad guy. \nThe cable breaks and you fall to your death. ");
                goButton.setText("Try Again");
                cButton.doClick();
                counter = 0;
            }
        }
        
        if (counter == 4)
        {
            outputField.setText("You choose not to load the ammo. \nYou continue down the hall ahead of you. \nA figure suddenly appears from around a corner\nand begins shooting at you. \nThe room is also full of support pillars\nA = hide behind the pillars \nB = Shoot back");
            if(bButton.isSelected())
            {
                cButton.doClick();
            }
            if(aButton.isSelected())
            {
            outputField.setText("You load the ammo into your gun. \nDown the hall, a figure suddenly starts shooting at you. \nYou shoot back, but the ammo you\nloaded is rigged. \nIt blows up in your face.");
            goButton.setText("Try Again");
            cButton.doClick();
            counter = 0;
            }
        }
        
        if (counter == 5)
        {
            outputField.setText("You choose to hide behind the pillar. \nThe shooter advances on your position. \nYou quickly jump at the shooter and tackle\nhim to the ground. \nITS THE VILLAIN! \nA = Shoot him \nB = Stab him");
            if(aButton.isSelected())
            {
                cButton.doClick();
            }
            
            if(bButton.isSelected())
            {
                outputField.setText("You shoot back, but the shooter\nis wearing a bulletproof vest. \nYou are eventually shot to death.");
                goButton.setText("Try Again");
                cButton.doClick();
                counter = 0;
            }
        }
        
        if (counter == 6)
        {
            if(aButton.isSelected())
            {
                outputField.setText("You choose to stab the villain. \nIt works. \nYou win!");
                goButton.setText("Try Again");
                cButton.doClick();
                counter = 0;
            }
            
            if(bButton.isSelected())
            {
                outputField.setText("You try to shoot him through the head, \nbut your gun is empty! \nThe villain pulls out his knife\nand stabs you to death.");
                goButton.setText("Try Again");
                cButton.doClick();
                counter = 0;
            }
        }
    }//GEN-LAST:event_goButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adventureProgramGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adventureProgramGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adventureProgramGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adventureProgramGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adventureProgramGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aButton;
    private javax.swing.JRadioButton bButton;
    private javax.swing.JRadioButton cButton;
    private javax.swing.JButton goButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputField;
    private javax.swing.JLabel resultField;
    // End of variables declaration//GEN-END:variables
}
